// SPDX-License-Identifier: Apache-2.0
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, ChevronLeft, Upload } from "lucide-react";
import { useProjectApi, useTenant } from "../../tenant/TenantContext";
import { ApiError } from "../../api/types";
import type { EntityDiff, ImportMode, ImportResult } from "../../api/client";
import {
  Button,
  ConceptPopover,
  Input,
  PageBody,
  PageHeader,
  Section,
  cn,
  useToast,
} from "../../ui";

const SAMPLE_TREE = `.tessary/
├── pipeline/
│   ├── meta.yaml              (required)
│   ├── product_profile.yaml
│   ├── invariants.yaml
│   ├── chains.yaml
│   ├── taxonomy.yaml
│   ├── packs.yaml
│   ├── call_sites/
│   │   └── <id>.yaml
│   └── failure_modes/
│       └── <call_site_id>.yaml
├── graders/
│   └── <call_site>/
│       └── <failure>.yaml
├── datasets/
│   └── <call_site_id>.jsonl
└── report.md`;

export function ImportYaml() {
  const api = useProjectApi();
  const { orgSlug, projectSlug } = useTenant();
  const nav = useNavigate();
  const qc = useQueryClient();
  const toast = useToast();
  const [mode, setMode] = useState<ImportMode>("upsert");
  const [dirFiles, setDirFiles] = useState<File[]>([]);
  // Replace is destructive, so it cannot be submitted until the operator types
  // the project slug back to confirm intent. Upsert never gates on this.
  const [confirmText, setConfirmText] = useState("");

  // Import lands grader DEFINITIONS only — generation never fires automatically. The
  // "generate prompts & code" action lives on the Pipeline page (and the setup wizard);
  // after a successful import we point there.

  const runImport = useMutation({
    mutationFn: async (): Promise<ImportResult> => api.importEvalsDirectory(dirFiles, mode),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["pipeline"] });
      qc.invalidateQueries({ queryKey: ["curation"] });
      setDirFiles([]);
      setConfirmText("");
    },
    onError: (err) => {
      const msg = (err as ApiError).message ?? "Import failed";
      toast.error("Import failed", msg);
    },
  });

  const summary = summariseDirSelection(dirFiles);
  const replaceConfirmed = mode !== "replace" || confirmText.trim() === projectSlug;
  const canSubmit = dirFiles.length > 0 && summary.hasPipelineMeta && replaceConfirmed;

  return (
    <PageBody size="narrow">
      <button
        type="button"
        onClick={() => nav(`/orgs/${orgSlug}/projects/${projectSlug}/settings/sources`)}
        className="mb-3 flex items-center gap-1.5 text-small text-muted transition-colors hover:text-fg"
        style={{ transitionDuration: "var(--duration-micro)" }}
      >
        <ChevronLeft size={12} strokeWidth={1.5} aria-hidden="true" />
        Back to Sources
      </button>
      <PageHeader
        eyebrow="Data & ingestion"
        title="Import bundle"
        subtitle={
          <>
            Update this project's pipeline from a <code className="font-mono text-fg">.tessary/</code>{" "}
            bundle generated by the <ConceptPopover concept="pipeline">evals plugin</ConceptPopover>.
          </>
        }
      />

      <Section title="Source">
        <DirectoryPicker files={dirFiles} onChange={setDirFiles} summary={summary} />
        <details className="mt-3 group">
          <summary className="cursor-pointer text-small text-muted hover:text-fg select-none">
            What does a bundle look like?
          </summary>
          <pre className="mt-2 rounded-card border border-border bg-bg p-3 text-small font-mono text-muted overflow-x-auto">
            {SAMPLE_TREE}
          </pre>
        </details>
      </Section>

      <Section title="Mode">
        <div className="flex flex-col gap-3">
          <ModeOption
            value="upsert"
            current={mode}
            onChange={setMode}
            title="Upsert"
            desc="Adds new entities and updates changed ones. Your edits are kept."
            recommended
          />
          <ModeOption
            value="replace"
            current={mode}
            onChange={setMode}
            title="Replace"
            danger
            desc={
              <>
                Deletes the current pipeline first. <span className="text-error">All local edits are lost.</span> Type the project name to confirm.
              </>
            }
          />
        </div>

        {mode === "replace" && (
          <div className="mt-3 rounded-card border border-error p-4" style={{ backgroundColor: "var(--color-error-subtle)" }}>
            <div className="text-small text-fg">
              To replace, type the project name <code className="font-mono text-error">{projectSlug}</code> to confirm.
            </div>
            <Input
              value={confirmText}
              onChange={(e) => setConfirmText(e.target.value)}
              placeholder={projectSlug}
              className="mt-2"
              aria-label="Type the project name to confirm replace"
            />
          </div>
        )}
      </Section>

      {runImport.isSuccess && runImport.data && <ImportSummary result={runImport.data} />}

      <div className="flex items-center justify-end gap-2 mt-2">
        <Button
          variant={mode === "replace" ? "danger" : "primary"}
          onClick={() => runImport.mutate()}
          disabled={!canSubmit}
          loading={runImport.isPending}
        >
          {mode === "replace" ? "Replace pipeline" : "Import bundle"}
        </Button>
      </div>
    </PageBody>
  );
}

function ModeOption({
  value,
  current,
  onChange,
  title,
  desc,
  recommended,
  danger,
}: {
  value: ImportMode;
  current: ImportMode;
  onChange: (m: ImportMode) => void;
  title: string;
  desc: React.ReactNode;
  recommended?: boolean;
  danger?: boolean;
}) {
  const active = value === current;
  const accent = danger ? "var(--color-error)" : "var(--color-accent)";
  return (
    <button
      type="button"
      onClick={() => onChange(value)}
      className={cn(
        "relative text-left rounded-card border p-4 transition-colors",
        active && danger && "border-error",
        active && !danger && "border-accent bg-accent-subtle",
        !active && "border-border bg-surface hover:bg-hover",
      )}
      style={{ transitionDuration: "var(--duration-micro)" }}
    >
      <div className="flex items-center gap-2.5">
        <span
          className="inline-block size-4 rounded-pill border-2 flex-none"
          style={{ borderColor: active ? accent : "var(--color-border-strong)" }}
          aria-hidden="true"
        >
          {active && (
            <span
              className="block size-full rounded-pill"
              style={{ boxShadow: "inset 0 0 0 2px var(--color-bg)", backgroundColor: accent }}
            />
          )}
        </span>
        <span className={cn("text-small font-medium", danger ? "text-error" : "text-fg")}>{title}</span>
        {recommended && (
          <span className="ml-auto text-label uppercase text-accent">Recommended</span>
        )}
        {danger && (
          <span className="ml-auto inline-flex items-center gap-1.5 text-label uppercase text-error">
            <WarnGlyph />
            Destructive
          </span>
        )}
      </div>
      <p className="text-small text-muted mt-2 pl-[26px]">{desc}</p>
    </button>
  );
}

type DirSummary = {
  label: string;
  hasPipelineMeta: boolean;
  callSiteCount: number;
  failureModeShardCount: number;
  qualityDimensionShardCount: number;
  graderCount: number;
};

function DirectoryPicker({
  files,
  onChange,
  summary,
}: {
  files: File[];
  onChange: (next: File[]) => void;
  summary: DirSummary;
}) {
  const hasBundle = files.length > 0 && summary.hasPipelineMeta;
  return (
    <div className="space-y-2">
      {hasBundle ? (
        <div className="rounded-card border border-border p-4">
          <div className="flex items-center gap-2">
            <CheckGlyph />
            <span className="text-small text-fg">
              <code className="font-mono">.tessary/</code> read · <code className="font-mono text-fg">meta.yaml</code> found
            </span>
          </div>
          <div className="flex flex-wrap gap-x-6 gap-y-1 mt-3 text-small text-muted">
            <span>
              {summary.callSiteCount} <span className="text-fg">call sites</span>
            </span>
            <span>
              {summary.graderCount} <span className="text-fg">graders</span>
            </span>
            {summary.qualityDimensionShardCount > 0 && (
              <span>
                {summary.qualityDimensionShardCount} <span className="text-fg">quality dims</span>
              </span>
            )}
            <span>
              {files.length} <span className="text-fg">files</span>
            </span>
          </div>
          <PickerLabel onChange={onChange} className="mt-3 inline-flex">
            <span className="text-small text-muted hover:text-fg">Change selection</span>
          </PickerLabel>
        </div>
      ) : (
        <PickerLabel
          onChange={onChange}
          className={cn(
            "block rounded-card border border-dashed p-8 text-center cursor-pointer transition-colors",
            files.length === 0 ? "border-border-strong hover:bg-hover" : "border-warning",
          )}
        >
          <UploadGlyph />
          <div className="text-small text-fg mt-2.5">
            Choose a <code className="font-mono">.tessary/</code> directory, or drop it here
          </div>
          <div className="text-label text-muted mt-1.5">
            {files.length === 0 ? "Nothing selected yet" : summary.label}
          </div>
          <span className="inline-flex items-center justify-center h-8 px-3.5 mt-3.5 rounded-control bg-accent text-accent-text-on text-small font-medium">
            Choose directory
          </span>
        </PickerLabel>
      )}

      {files.length > 0 && !summary.hasPipelineMeta && (
        <div
          className="text-small px-3 py-2 rounded-card text-warning"
          style={{ backgroundColor: "var(--color-warning-subtle)" }}
        >
          No <code className="font-mono">pipeline/meta.yaml</code> in the selection. This directory doesn't look like a .tessary bundle.
        </div>
      )}

      {files.length > 0 && (
        <details>
          <summary className="text-small text-muted hover:text-fg cursor-pointer select-none">
            {files.length} file{files.length === 1 ? "" : "s"} selected
          </summary>
          <ul className="mt-1 text-small text-muted font-mono pl-3 max-h-40 overflow-y-auto">
            {files.slice(0, 30).map((f, i) => {
              const path = (f as File & { webkitRelativePath?: string }).webkitRelativePath || f.name;
              return <li key={i}>{path}</li>;
            })}
            {files.length > 30 && <li className="italic text-subtle">… and {files.length - 30} more</li>}
          </ul>
        </details>
      )}
    </div>
  );
}

function PickerLabel({
  onChange,
  className,
  children,
}: {
  onChange: (next: File[]) => void;
  className?: string;
  children: React.ReactNode;
}) {
  return (
    <label
      className={cn("cursor-pointer transition-colors", className)}
      style={{ transitionDuration: "var(--duration-micro)" }}
    >
      <input
        type="file"
        {...({ webkitdirectory: "", directory: "" } as Record<string, string>)}
        multiple
        className="hidden"
        onChange={(e) => {
          const list = e.target.files;
          if (!list) return;
          const next: File[] = [];
          for (let i = 0; i < list.length; i++) next.push(list[i]);
          onChange(next);
        }}
      />
      {children}
    </label>
  );
}

function ImportSummary({ result }: { result: ImportResult }) {
  const rows = changelogRows(result);
  return (
    <Section title="Import result">
      <div className="flex items-center gap-2 mb-3">
        <CheckGlyph />
        <span className="text-body font-medium text-fg">
          {result.mode === "replace" ? "Pipeline replaced" : "Pipeline updated"}
        </span>
      </div>
      <div className="rounded-card border border-border overflow-hidden font-mono text-small">
        {rows.length === 0 ? (
          <div className="px-3.5 py-2 text-muted">No changes. The pipeline already matched this bundle.</div>
        ) : (
          rows.map((r, i) => (
            <div
              key={i}
              className={cn(
                "px-3.5 py-2 leading-relaxed",
                i > 0 && "border-t border-border",
                r.tone === "added" && "text-success",
                r.tone === "orphaned" && "text-warning",
                r.tone === "plain" && "text-fg",
              )}
              style={
                r.tone === "added"
                  ? { backgroundColor: "var(--color-success-subtle)" }
                  : r.tone === "orphaned"
                    ? { backgroundColor: "var(--color-warning-subtle)" }
                    : undefined
              }
            >
              {r.glyph} {r.text}
              {r.note && <span className="text-muted"> {r.note}</span>}
            </div>
          ))
        )}
      </div>
    </Section>
  );
}

type ChangeRow = {
  tone: "added" | "plain" | "orphaned";
  glyph: string;
  text: string;
  note?: string;
};

function changelogRows(result: ImportResult): ChangeRow[] {
  const rows: ChangeRow[] = [];
  const entities: { label: string; d: EntityDiff }[] = [
    { label: "call sites", d: result.callSites },
    { label: "chains", d: result.chains },
    { label: "failure modes", d: result.failureModes },
    { label: "quality dimensions", d: result.qualityDimensions },
    { label: "graders", d: result.graders },
  ];
  for (const { label, d } of entities) {
    if (d.added > 0) rows.push({ tone: "added", glyph: "+", text: `${d.added} ${label} added` });
    if (d.updated > 0)
      rows.push({
        tone: "plain",
        glyph: "~",
        text: `${d.updated} ${label} updated`,
        note: label === "graders" ? "(your edits kept)" : undefined,
      });
    if (d.removed > 0) rows.push({ tone: "plain", glyph: "-", text: `${d.removed} ${label} removed` });
  }
  if (result.orphanedAfterImport > 0) {
    rows.push({
      tone: "orphaned",
      glyph: "!",
      text: `${result.orphanedAfterImport} curation ${result.orphanedAfterImport === 1 ? "entry" : "entries"} orphaned: their call site is gone`,
    });
  }
  return rows;
}

function summariseDirSelection(files: File[]): DirSummary {
  let hasPipelineMeta = false;
  let callSiteCount = 0;
  let failureModeShardCount = 0;
  let qualityDimensionShardCount = 0;
  let graderCount = 0;
  for (const f of files) {
    const path = ((f as File & { webkitRelativePath?: string }).webkitRelativePath || f.name).toLowerCase();
    if (!(path.endsWith(".yaml") || path.endsWith(".yml"))) continue;
    if (
      path.endsWith("/pipeline/meta.yaml") ||
      path === "pipeline/meta.yaml" ||
      path.endsWith("/pipeline/meta.yml") ||
      path === "pipeline/meta.yml"
    ) {
      hasPipelineMeta = true;
    } else if (path.includes("/pipeline/call_sites/")) {
      callSiteCount++;
    } else if (path.includes("/pipeline/failure_modes/")) {
      failureModeShardCount++;
    } else if (path.includes("/pipeline/quality_dimensions/")) {
      qualityDimensionShardCount++;
    } else if (path.includes("/graders/")) {
      graderCount++;
    }
  }
  const parts: string[] = [];
  parts.push(hasPipelineMeta ? "meta.yaml ✓" : "meta.yaml missing");
  parts.push(`${callSiteCount} call site${callSiteCount === 1 ? "" : "s"}`);
  parts.push(`${graderCount} grader${graderCount === 1 ? "" : "s"}`);
  if (qualityDimensionShardCount > 0)
    parts.push(`${qualityDimensionShardCount} quality dim shard${qualityDimensionShardCount === 1 ? "" : "s"}`);
  parts.push(`${files.length} total`);
  return {
    label: parts.join(" · "),
    hasPipelineMeta,
    callSiteCount,
    failureModeShardCount,
    qualityDimensionShardCount,
    graderCount,
  };
}

// ---- glyphs ------------------------------------------------------------------

function CheckGlyph() {
  return <CheckCircle2 size={15} strokeWidth={1.6} aria-hidden="true" className="text-success flex-none" />;
}

function UploadGlyph() {
  return <Upload size={22} strokeWidth={1.5} aria-hidden="true" className="text-muted inline-block" />;
}

function WarnGlyph() {
  return <AlertTriangle size={12} strokeWidth={1.5} aria-hidden="true" />;
}
