# SPDX-License-Identifier: Apache-2.0
"""RAGTruth as an evaluation corpus: real LLM outputs, real retrieved passages, HUMAN labels.

WHY THIS CORPUS. Every held-out set in this module so far was generated by one Claude model and
verified by another. That controls for the generator's habits (the `--hard` corpus) and for corpus
design flaws (the `compound_support` control), but it cannot control for what two language models
writing to a spec both fail to imagine. RAGTruth (Niu et al., MIT licence) is 17,790 responses from
six production LLMs — GPT-4, GPT-3.5, Mistral-7B, three Llama-2 sizes — over real retrieved
context, with span-level annotations by human annotators. It is the first number here that does not
route through a Claude model at any stage.

THE LABEL MAP IS THE WHOLE POINT, AND IT IS EXACT. RAGTruth's annotators distinguish two failure
kinds, and they are the same two this classifier distinguishes:

    Evident Conflict / Subtle Conflict   ->  the output CONTRADICTS the source   ->  positive
    Evident Baseless / Subtle Baseless   ->  the source is SILENT on the claim   ->  NEGATIVE

That second line is not a shortcut. `labels.py` says in as many words that an unsupported addition
is deliberately out of scope, because it is input-identical to a true fact from a tool call.
RAGTruth's `baseless_info` is that class, labelled by humans, at scale — so this corpus tests the
scope decision as well as the model: a classifier that fires on baseless spans is spending its FP
budget on exactly what it promised not to flag.

WHAT IS EXCLUDED. `Data2txt` (900 of the 2,700 test responses) renders a JSON object into prose.
The premise is structured data, which the catalog entry withdraws as an evidence carrier — the NLI
head cannot read a JSON object as a premise, and scoring it would report the classifier's stated
blind spot as a failure. Summary and QA remain: 1,775 responses after the `quality == "good"` filter.

THE UNIT IS THE SENTENCE. The classifier scores one asserted sentence against the premise; the
annotations are character spans in the response. A sentence is positive if any conflict span
overlaps it. This is also roughly what `VerifiableClaims` hands the head in production.

PREVALENCE IS REALISTIC HERE, AND THAT CHANGES WHAT THE NUMBERS MEAN. 1.5% of Summary/QA
sentences (143 of 9,540) carry a conflict, against 40% in the generated corpora. Recall and FP
rate are prevalence-free; precision is not: at 1.5% prevalence a 2% FP rate on 9,397 negatives is
~188 false fires against at most 143 true ones, so precision here CANNOT exceed ~0.43 even at
perfect recall. That is not a defect of the model — it is what a 2% FP budget means on data where
contradictions are rare, and it is the number a deployment with realistic traffic will see.
"""

from __future__ import annotations

import json
import re
from typing import Iterable

from .pairs import Pair

CONFLICT = {"Evident Conflict", "Subtle Conflict"}
BASELESS = {"Evident Baseless Info", "Subtle Baseless Info"}
TASKS = ("Summary", "QA")

_SENT = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9\"'(])")
MIN_SENT_CHARS = 20


def _sentences(text: str) -> Iterable[tuple[int, int, str]]:
    """(start, end, sentence) with character offsets into `text`, so spans can be aligned."""
    pos = 0
    for m in _SENT.finditer(text):
        yield pos, m.start(), text[pos : m.start()]
        pos = m.end()
    yield pos, len(text), text[pos:]


def load(split: str = "test") -> tuple[list[Pair], dict]:
    from datasets import load_dataset

    rows = load_dataset("wandb/RAGTruth-processed")[split]
    pairs: list[Pair] = []
    kept = 0
    for r in rows:
        if r["task_type"] not in TASKS or r["quality"] != "good":
            continue
        kept += 1
        spans = json.loads(r["hallucination_labels"])
        conflicts = [(s["start"], s["end"]) for s in spans if s.get("label_type") in CONFLICT]
        baseless = [(s["start"], s["end"]) for s in spans if s.get("label_type") in BASELESS]
        documents = tuple(d.strip() for d in r["context"].split("\n\n") if d.strip())
        for start, end, sent in _sentences(r["output"]):
            sent = sent.strip()
            if len(sent) < MIN_SENT_CHARS:
                continue
            hits_conflict = any(a < end and b > start for a, b in conflicts)
            hits_baseless = any(a < end and b > start for a, b in baseless)
            kind = "conflict" if hits_conflict else "baseless" if hits_baseless else "clean"
            pairs.append(
                Pair(
                    documents=documents,
                    premise="\n\n".join(documents),
                    claim=sent,
                    label=1 if hits_conflict else 0,
                    source=f"ragtruth:{r['id']}",
                    slices={
                        "kind": kind,
                        "shape": r["task_type"].lower(),
                        "domain": r["model"],
                        "decontextualized": "false",
                        # Sentences of one response share a premise and are NOT independent; this
                        # is the clustering unit for the bootstrap and for CV folds.
                        "cluster": str(r["id"]),
                    },
                )
            )
    meta = {
        "corpus": "ragtruth",
        "split": split,
        "responses": kept,
        "licence": "MIT",
        "kappa": None,
        "claims": [{"kind": p.slices["kind"]} for p in pairs],
    }
    return pairs, meta


def summary(split: str = "test") -> str:
    from collections import Counter

    pairs, meta = load(split)
    kinds = Counter(p.slices["kind"] for p in pairs)
    tasks = Counter(p.slices["shape"] for p in pairs)
    models = Counter(p.slices["domain"] for p in pairs)
    pos = sum(1 for p in pairs if p.label == 1)
    lines = [
        f"RAGTruth {split}: {meta['responses']} Summary/QA responses -> {len(pairs)} sentences",
        f"  positive (conflict): {pos}  ({pos / len(pairs):.1%} prevalence)",
        f"  by kind: {dict(kinds)}",
        f"  by task: {dict(tasks)}",
        f"  by model: {dict(models)}",
        f"  documents per premise: mean {sum(len(p.documents) for p in pairs) / len(pairs):.1f}, "
        f"premise chars: mean {sum(len(p.premise) for p in pairs) / len(pairs):.0f}",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    print(summary())
