#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# =============================================================================
# Populated-database migration gate — run the new migrations against ROWS
# =============================================================================
# docs/reference/PLAN-1-cleanup-release.md §2 rule 2. `task check` applies Liquibase to an
# EMPTY Testcontainers database (TestPostgres.createIsolatedDatabase), and an empty database
# structurally cannot fail the two ways a rename fails:
#
#   1. `ALTER TABLE … ADD CONSTRAINT … CHECK (col = ANY (ARRAY['new', …]))` validates
#      every existing row. With no rows it always passes. With one row still holding
#      'old' it aborts the deploy — and that is the constraint swap the whole release
#      is made of.
#   2. `UPDATE … SET col='new' WHERE col='old'` that matches ZERO rows is
#      indistinguishable from one that matches all of them. Where no CHECK backs the
#      column (metric_rollup.metric, the alert_event payload keys) nothing fails at all:
#      the reader just starts seeing zero, not an error.
#
# So this script builds a database that HAS those rows, and asserts.
#
# TWO LANES (2026-09, #1074). The DB baseline is partitioned: the open tables (64 at the
# partition, a count the partition derived from its own dump rather than typed) live in
# backend/core's 0000-baseline.sql, 15 paid tables live in the paid overlay module's own
# P0000-paid-baseline.sql, applied by a second Liquibase bean strictly after the open one. This
# script mirrors that with two lanes of its own:
#
#   OPEN LANE (always runs)     — open-old chain, open fixture, open-new chain, the always-run
#                                  half of fixture-coverage.
#   OVERLAY LANE (opt-in)       — overlay-old chain, paid fixture, overlay-new chain, the
#                                  overlay-gated half of fixture-coverage. Runs only when
#                                  MIGPOP_OVERLAY_DIR is set (mirroring Taskfile.yml's own
#                                  file-exists guard on whether the overlay is present at
#                                  all) — an open-alone checkout has no paid tables to seed or
#                                  assert on, and skipping the lane is not the same as skipping
#                                  the proof: the open half still asserts everything an open
#                                  checkout owns.
#
# Six steps against ONE throwaway container, in this order — open-old before overlay-old
# because the paid overlay's own floor-pin precondition (real db.changelog-paid.yaml, used for
# the OVERLAY-NEW apply below) requires evals:0000-baseline to already be in databasechangelog;
# paid-fixture after overlay-old because its rows FK against tables overlay-old just created;
# open-fixture before overlay-old (not after) because the paid fixture's rows ALSO FK against
# the open fixture's anchor rows (prj_fix, cls_fix, org_fix):
#
#   open-old chain    → the open changelog up to and including MIGPOP_BASELINE, regenerated by
#                        cutting the current open master's include list at that file.
#   open fixture      → scripts/lib/populated-fixture.sql.
#   overlay-old chain → [overlay lane only] the paid changelog up to and including
#                        MIGPOP_OVERLAY_BASELINE, regenerated the same way, its floor-pin
#                        preConditions block stripped (unneeded for this throwaway apply — the
#                        floor, evals:0000-baseline, is already satisfied by open-old above; the
#                        real pin is what OVERLAY-NEW below exercises).
#   paid fixture      → [overlay lane only] MIGPOP_OVERLAY_FIXTURE
#                        (derived from MIGPOP_OVERLAY_DIR by default — see below); its coverage
#                        claims are MIGPOP_OVERLAY_EXPECTS, a sourced fragment beside it.
#   fixture-coverage   → a query per claim that a fixture row loaded. Runs BEFORE the new chains,
#                        so a table a migration drops is still queryable here.
#   open-new chain     → the current open master, i.e. every migration after MIGPOP_BASELINE,
#                        applied on top of populated tables.
#   overlay-new chain  → [overlay lane only] the REAL db.changelog-paid.yaml (floor-pin intact),
#                        i.e. every paid migration after MIGPOP_OVERLAY_BASELINE.
#   assertions         → one block per release with a migration in flight (none in either lane
#                        today — see "WHERE THIS STANDS TODAY" below).
#
# WHERE THIS STANDS TODAY. The 2026-09 cutover re-baseline (#1144) folded the 0017-0023 chain
# into 0000-baseline.sql, as the partition before it (#1074) folded 0001-0016 and moved 15 tables
# out to a brand-new P0000-paid-baseline.sql. So both lanes' "new chain" is empty today — every
# assertion that used to live in a release block below tested migrations that are now INSIDE the
# baseline on both sides of the old/new cut, which is exactly the failure the "MOVING THE
# BASELINE" rule below warns about: an assertion that reads as PASS against migrations nothing
# here still applies separately. Each fold deleted its own: the partition deleted six (the five
# "Model lane cutover"/"Triage cutover" blocks that tested 0004-0007 and 0009, and the "Track A
# removal" block that tested 0016, which landed on main as PR #1095 BEFORE the partition and so
# was folded with the rest), and #1144 deleted the seventh, "Phase 0017", which tested the
# vector/embedding substrate's removal. Those blocks, and the fixture rows that existed only to
# feed them, were deleted in the same commit that folded their chain (their rows: saved_view, two behaviour-review job rows,
# finding's now-nonexistent review columns, the retired lanes of project_model_setting/llm_call,
# and Track A's: the environment rows, the dropped tables' rows, the colliding metric_rollup and
# metric_baseline rows, the four retired job kinds, the verdict retention class — the folded
# baseline's own CHECK constraints no longer admit several of those values at all, and several of
# the tables no longer exist, so keeping the rows would have broken the fixture LOAD, not just
# left an assertion stale). The fixture still holds the rows a rename or a drop has to move for
# whatever lands next; a new migration that touches a persisted value only needs its assertions
# written below.
#
# WHY THE BASELINES ARE PINNED FILENAMES AND NOT `git merge-base HEAD origin/main`. Each fixture
# is written against ONE schema — its lane's baseline — and a merge-base cut produces that schema
# only while a release is unmerged. The moment it lands on main, every file in it exists at
# merge-base too, the "old" chain silently becomes the FULL chain, and the fixture fails to
# load against a schema its own release already renamed. The gate would then read as fixture
# rot rather than as a tool that had expired, and it would be runnable exactly once, by hand,
# before merge. Pinned, it stays runnable forever — which is what makes it a gate the next
# release can also point at its own renames.
#
# MOVING A BASELINE. Bump one (or pass MIGPOP_BASELINE= / MIGPOP_OVERLAY_BASELINE=) only
# together with a fixture that loads against the new baseline's schema and assertions that
# match — i.e. when a release's renames are done and the NEXT release wants this vehicle.
# Bumping it alone turns the whole file into assertions about migrations that are already
# inside the "old" chain, which pass without proving anything.
#
# WHY THE LIQUIBASE CLI IMAGE. The app's only in-process Liquibase path is
# SpringLiquibase at boot (backend/core/.../db/LiquibaseConfig.java for the open lane,
# PaidDbAutoConfiguration for the paid one), which needs the full application context —
# datasource, WorkOS config, the lot — to apply a changelog. The CLI image needs a JDBC URL.
# Every apply here goes through the SAME tool, which is what makes the before/after comparison
# meaningful, and this database is throwaway, so nothing about the app's own runtime is being
# simulated or asserted. The image ships no Postgres driver, so the driver is taken from the
# local Maven repository — the one the backend already builds against.
#
# NOT-YET-APPLICABLE ASSERTIONS. Each release's assertions go in a block gated on a schema
# fact its own migration establishes, so a migration that has not landed reports SKIP and
# never PASS: a gate that passes vacuously is worse than no gate.
#
# The fixture-coverage block runs ALWAYS (its open half) or when the overlay lane is on (its
# overlay half), and is the guard on the guard: it fails if a value this script asserts on never
# made it into the fixture, so a SKIP in the release-block section always means "the migration is
# not here yet", never "the row was not here either".
#
# Usage:  ./scripts/check-migrations-populated.sh [--keep]
#           --keep   leave the container running for poking at; prints the psql line
#
#         MIGPOP_OVERLAY_DIR=<absolute path to the paid overlay's resources root> ./scripts/check-migrations-populated.sh
#           turns the overlay lane on — a paid module's resources root, holding
#           db/changelog/paid/db.changelog-paid.yaml. Unset (the default): open lane only.
#         MIGPOP_OVERLAY_FIXTURE=<path>     default: scripts/lib/paid-populated-fixture.sql, sibling to
#                                            the overlay module MIGPOP_OVERLAY_DIR names
#         MIGPOP_OVERLAY_EXPECTS=<path>     default: paid-populated-expects.sh beside the paid fixture;
#                                            the overlay's own expect() calls, sourced in the overlay lane
#         MIGPOP_OVERLAY_BASELINE=<file>    default P0000-paid-baseline.sql
#
# Requires: docker and a Postgres JDBC driver in ~/.m2 (any backend build puts one
# there). Takes a couple of minutes on one CPU; leaves nothing behind.
#
# Not wired into `task check` or CI, deliberately: it is worth running exactly when a migration
# renames or narrows a persisted value, and it is dead weight on every other change. Run it per
# phase — `task migrations:populated` — before merging one that does. Taskfile.yml's
# `migrations:populated` task runs the overlay lane automatically when the paid overlay is present
# (mirroring `overlay:apply-changelog`'s own file-exists guard), so a paid
# checkout gets both lanes without passing the env vars by hand.
# =============================================================================

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESOURCES="backend/core/src/main/resources"
MASTER="$RESOURCES/db/changelog/db.changelog-master.yaml"

CONTAINER="evals-migrations-populated"
NETWORK="evals-migrations-populated-net"
# Deliberately not 5433 (the dev stack) or 55555 (restore-drill.sh): this must be
# runnable while either of those is up.
PORT="${MIGPOP_PORT:-55432}"
PG_IMAGE="${MIGPOP_PG_IMAGE:-pgvector/pgvector:pg16}"
LB_IMAGE="${MIGPOP_LB_IMAGE:-liquibase/liquibase:5.0}"
DB="evals"
PASSWORD="migpop"
KEEP=0

# The last changeset the open fixture is written against — everything after it is what this
# gate runs against rows. See "WHY THE BASELINES ARE PINNED FILENAMES" above before moving it.
BASELINE="${MIGPOP_BASELINE:-0000-baseline.sql}"

# The overlay lane. Unset MIGPOP_OVERLAY_DIR is "no paid overlay in this checkout" — every
# overlay-lane step below is skipped, not failed, the same file-exists guard shape
# Taskfile.yml's own overlay:apply-changelog task already uses.
OVERLAY_DIR="${MIGPOP_OVERLAY_DIR:-}"
# The overlay's own directory name is never spelled out literally in this file on purpose
# (check-open-boundary.sh rule 5: an open script may not name the overlay module by path — only
# the four scripts whose whole job IS managing it may, and this is not one of them). The fixture
# default below is derived from MIGPOP_OVERLAY_DIR itself
# (<overlay module>/db/src/main/resources -> <overlay module>/scripts/lib/...), which the caller
# supplies — Taskfile.yml's migrations:populated task, itself an orchestration file allowed to
# name the overlay under its own guard.
OVERLAY_FIXTURE="${MIGPOP_OVERLAY_FIXTURE:-}"
if [ -n "$OVERLAY_DIR" ] && [ -z "$OVERLAY_FIXTURE" ]; then
  OVERLAY_MODULE_ROOT="$(dirname "$(dirname "$(dirname "$(dirname "$OVERLAY_DIR")")")")"
  OVERLAY_FIXTURE="$OVERLAY_MODULE_ROOT/scripts/lib/paid-populated-fixture.sql"
fi
OVERLAY_EXPECTS="${MIGPOP_OVERLAY_EXPECTS:-}"
if [ -n "$OVERLAY_DIR" ] && [ -z "$OVERLAY_EXPECTS" ]; then
  OVERLAY_EXPECTS="$(dirname "$OVERLAY_FIXTURE")/paid-populated-expects.sh"
fi
OVERLAY_BASELINE="${MIGPOP_OVERLAY_BASELINE:-P0000-paid-baseline.sql}"

[ "${1:-}" != "--keep" ] || KEEP=1

die() {
  echo "check-migrations-populated: FAIL — $*" >&2
  exit 1
}

WORK="$(mktemp -d -t evals-migpop.XXXXXX)"
cleanup() {
  rm -rf "$WORK"
  if [ "$KEEP" != 1 ]; then
    docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    docker network rm "$NETWORK" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

# ---------------------------------------------------------------- preflight

cd "$ROOT"
command -v docker >/dev/null || die "docker is required"
[ -f "$MASTER" ] || die "no master changelog at $MASTER"
[ -f scripts/lib/populated-fixture.sql ] || die "no fixture at scripts/lib/populated-fixture.sql"

DRIVER="$(find "$HOME/.m2/repository/org/postgresql/postgresql" -name 'postgresql-*.jar' 2>/dev/null \
  | grep -v -- '-sources' | sort -V | tail -1 || true)"
[ -n "$DRIVER" ] || die "no Postgres JDBC driver under ~/.m2 — build the backend once (mvn -f backend/pom.xml -q -DskipTests package) so the driver is resolved"

[ -f "$RESOURCES/db/changelog/changes/$BASELINE" ] || die "no baseline changeset at $RESOURCES/db/changelog/changes/$BASELINE"

if [ -n "$OVERLAY_DIR" ]; then
  OVERLAY_MASTER="$OVERLAY_DIR/db/changelog/paid/db.changelog-paid.yaml"
  [ -f "$OVERLAY_MASTER" ] || die "MIGPOP_OVERLAY_DIR ${OVERLAY_DIR} has no db/changelog/paid/db.changelog-paid.yaml"
  [ -f "$OVERLAY_FIXTURE" ] || die "MIGPOP_OVERLAY_FIXTURE ${OVERLAY_FIXTURE} does not exist"
  [ -f "$OVERLAY_DIR/db/changelog/paid/changes/$OVERLAY_BASELINE" ] \
    || die "no overlay baseline changeset at $OVERLAY_DIR/db/changelog/paid/changes/$OVERLAY_BASELINE"
fi

# ---------------------------------------------------------------- the open changelogs
# The old master is the current master's include list cut at BASELINE. Deriving it from the
# CURRENT master (rather than checking out an old one) keeps the include order authoritative
# and means a reordering shows up here.

mkdir -p "$WORK/resources"
cp -R "$RESOURCES/db" "$WORK/resources/db"
CHANGELOG_DIR="$WORK/resources/db/changelog"

OLD_MASTER="$CHANGELOG_DIR/db.changelog-old.yaml"
{
  echo "# Generated by scripts/check-migrations-populated.sh — the open chain through $BASELINE."
  echo "databaseChangeLog:"
} >"$OLD_MASTER"

NEW_FILES=""
OLD_COUNT=0
NEW_COUNT=0
PAST_BASELINE=0
while IFS= read -r file; do
  if [ "$PAST_BASELINE" = 0 ]; then
    printf '  - include:\n      file: %s\n      relativeToChangelogFile: false\n' "$file" >>"$OLD_MASTER"
    OLD_COUNT=$((OLD_COUNT + 1))
    [ "${file##*/}" != "$BASELINE" ] || PAST_BASELINE=1
  else
    NEW_FILES="$NEW_FILES ${file##*/}"
    NEW_COUNT=$((NEW_COUNT + 1))
  fi
done < <(sed -n 's|^ *file: *\(db/changelog/changes/.*\)$|\1|p' "$MASTER")

[ "$OLD_COUNT" -gt 0 ] || die "the generated old chain is empty — is $MASTER in the expected include format?"
[ "$PAST_BASELINE" = 1 ] || die "$BASELINE is on disk but not in $MASTER's include list — the baseline must be a changeset the chain actually applies"

echo "check-migrations-populated: open lane — old chain ${OLD_COUNT} file(s) through ${BASELINE}, new ${NEW_COUNT} file(s):${NEW_FILES:- none}"

# ---------------------------------------------------------------- the overlay changelogs
# Same cut-at-baseline derivation as the open lane, sourced from the overlay's OWN master
# rather than the open one, and with the floor-pin preConditions block left out entirely (not
# carried over and stripped — regenerated from scratch, so there is nothing to strip): the
# throwaway "old" apply below runs strictly after open-old in the SAME database, so the floor
# (evals:0000-baseline in databasechangelog) is already satisfied by the time it would be
# checked. The REAL floor-pin is what OVERLAY-NEW exercises, using $OVERLAY_MASTER unmodified.

OVERLAY_NEW_COUNT=0
OVERLAY_NEW_FILES=""
if [ -n "$OVERLAY_DIR" ]; then
  mkdir -p "$WORK/resources-overlay"
  cp -R "$OVERLAY_DIR/db" "$WORK/resources-overlay/db"
  OVERLAY_CHANGELOG_DIR="$WORK/resources-overlay/db/changelog/paid"

  OVERLAY_OLD_MASTER="$OVERLAY_CHANGELOG_DIR/db.changelog-paid-old.yaml"
  {
    echo "# Generated by scripts/check-migrations-populated.sh — the overlay chain through $OVERLAY_BASELINE, floor-pin stripped."
    echo "databaseChangeLog:"
  } >"$OVERLAY_OLD_MASTER"

  OVERLAY_OLD_COUNT=0
  OVERLAY_PAST_BASELINE=0
  while IFS= read -r file; do
    if [ "$OVERLAY_PAST_BASELINE" = 0 ]; then
      printf '  - include:\n      file: %s\n      relativeToChangelogFile: false\n' "$file" >>"$OVERLAY_OLD_MASTER"
      OVERLAY_OLD_COUNT=$((OVERLAY_OLD_COUNT + 1))
      [ "${file##*/}" != "$OVERLAY_BASELINE" ] || OVERLAY_PAST_BASELINE=1
    else
      OVERLAY_NEW_FILES="$OVERLAY_NEW_FILES ${file##*/}"
      OVERLAY_NEW_COUNT=$((OVERLAY_NEW_COUNT + 1))
    fi
  done < <(sed -n 's|^ *file: *\(db/changelog/paid/changes/.*\)$|\1|p' "$OVERLAY_MASTER")

  [ "$OVERLAY_OLD_COUNT" -gt 0 ] || die "the generated overlay-old chain is empty — is $OVERLAY_MASTER in the expected include format?"
  [ "$OVERLAY_PAST_BASELINE" = 1 ] \
    || die "$OVERLAY_BASELINE is on disk but not in $OVERLAY_MASTER's include list — the overlay baseline must be a changeset the chain actually applies"

  echo "check-migrations-populated: overlay lane — old chain ${OVERLAY_OLD_COUNT} file(s) through ${OVERLAY_BASELINE}, new ${OVERLAY_NEW_COUNT} file(s):${OVERLAY_NEW_FILES:- none}"
else
  echo "check-migrations-populated: overlay lane skipped — MIGPOP_OVERLAY_DIR is not set"
fi

# ---------------------------------------------------------------- throwaway postgres

docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
docker network create "$NETWORK" >/dev/null 2>&1 || true
docker run --rm -d --name "$CONTAINER" --network "$NETWORK" \
  -e POSTGRES_PASSWORD="$PASSWORD" -e POSTGRES_DB="$DB" \
  -p "${PORT}:5432" "$PG_IMAGE" >/dev/null || die "could not start $PG_IMAGE on :${PORT}"

for _ in $(seq 1 90); do
  docker exec "$CONTAINER" pg_isready -U postgres >/dev/null 2>&1 && break
  sleep 1
done
docker exec "$CONTAINER" pg_isready -U postgres >/dev/null 2>&1 || die "postgres never became ready on :${PORT}"

# One function, both lanes: $2 is the resources root to mount (open or overlay), so the same
# tool applies both — see "WHY THE LIQUIBASE CLI IMAGE" above.
liquibase_update() {
  local label="$1" resources="$2" changelog="$3" log="$WORK/liquibase-${1// /-}.log"
  if ! docker run --rm --network "$NETWORK" \
      -v "$resources:/liquibase/changelog:ro" \
      -v "$DRIVER:/liquibase/lib/postgresql.jar:ro" \
      "$LB_IMAGE" --headless=true --logLevel=warning \
      --url="jdbc:postgresql://${CONTAINER}:5432/${DB}" --username=postgres --password="$PASSWORD" \
      --searchPath=/liquibase/changelog --changeLogFile="$changelog" \
      update >"$log" 2>&1; then
    # Stack frames drown the one line that matters ("… is violated by some row"), and
    # that line is the whole point of this gate, so they are filtered out.
    echo "--- liquibase output ($label chain, stack frames elided) ---" >&2
    { grep -v '^[[:space:]]*at ' "$log" || true; } | tail -30 >&2
    die "the ${label} chain did not apply"
  fi
}

q() {
  docker exec "$CONTAINER" psql -U postgres -d "$DB" -tAc "$1" 2>/dev/null | tr -d '[:space:]'
}

# ---------------------------------------------------------------- assertions plumbing

FAILURES=0
SKIPPED=0
expect() {
  local label="$1" want="$2" sql="$3" got
  got="$(q "$sql" || true)"
  if [ "$got" = "$want" ]; then
    printf '  PASS  %-58s %s\n' "$label" "$got"
  else
    printf '  FAIL  %-58s got %s, want %s\n' "$label" "${got:-<query error>}" "$want"
    FAILURES=$((FAILURES + 1))
  fi
}
skip() {
  printf '  SKIP  %-58s %s\n' "$1" "$2"
  SKIPPED=$((SKIPPED + 1))
}

# ---------------------------------------------------------------- 1. open-old, open-fixture

echo "check-migrations-populated: applying the open-old chain"
liquibase_update "open old" "$WORK/resources" db/changelog/db.changelog-old.yaml

echo "check-migrations-populated: loading the open fixture"
docker exec -i "$CONTAINER" psql -v ON_ERROR_STOP=1 -U postgres -d "$DB" -q \
  <scripts/lib/populated-fixture.sql \
  || die "the open fixture did not load against the open-old chain — it has drifted from the schema through ${BASELINE}"

# ---------------------------------------------------------------- 2. overlay-old, paid-fixture

if [ -n "$OVERLAY_DIR" ]; then
  echo "check-migrations-populated: applying the overlay-old chain"
  liquibase_update "overlay old" "$WORK/resources-overlay" db/changelog/paid/db.changelog-paid-old.yaml

  echo "check-migrations-populated: loading the paid fixture"
  docker exec -i "$CONTAINER" psql -v ON_ERROR_STOP=1 -U postgres -d "$DB" -q \
    <"$OVERLAY_FIXTURE" \
    || die "the paid fixture (${OVERLAY_FIXTURE}) did not load against the overlay-old chain — it has drifted from the schema through ${OVERLAY_BASELINE}"
fi

echo
echo "fixture coverage (every value a rename could touch must be present BEFORE the new chains)"
echo "-- open lane, always --"
expect "job.kind='classifier'"                1 "SELECT count(*) FROM job WHERE kind='classifier'"
expect "classifier row"                       1 "SELECT count(*) FROM classifier"
expect "eval_case.detector='classifier'"      2 "SELECT count(*) FROM eval_case WHERE detector='classifier'"
expect "eval_case both finding arms"          2 "SELECT (SELECT count(*) FROM eval_case WHERE finding_id IS NOT NULL)
                                                      + (SELECT count(*) FROM eval_case WHERE finding_id IS NULL AND state='resolved')"
expect "finding rows"                         1 "SELECT count(*) FROM finding"
expect "annotation all three grains"          3 "SELECT count(DISTINCT subject_kind) FROM annotation"
expect "failure_mode_instance both grains"    2 "SELECT count(DISTINCT subject_kind) FROM failure_mode_instance"
expect "metric_rollup metering metrics"       2 "SELECT count(*) FROM metric_rollup WHERE metric IN ('l1_evals','l2_evals')"
expect "metric_baseline row"                  1 "SELECT count(*) FROM metric_baseline WHERE bucket_key='cs_fix'"
expect "retention_policy both classes"        2 "SELECT count(DISTINCT data_class) FROM retention_policy
                                                   WHERE data_class IN ('traces','detections')"
expect "alert_event payload classifier keys"  1 "SELECT count(*) FROM alert_event WHERE payload_json LIKE '%\"classifiers\"%' AND payload_json LIKE '%\"classifier_key\"%'"
expect "pre_deploy_check rows"                1 "SELECT count(*) FROM pre_deploy_check"
# The old six-table detection UNION view is gone (#1074); these are its three OPEN arms, asked
# directly. All three fixture rows are span-grain (see scripts/lib/populated-fixture.sql), which
# is the fact this checks rather than assuming.
expect "open detection rows across the three open tables" 3 "SELECT (SELECT count(*) FROM secret_leak_detection)
                                                      + (SELECT count(*) FROM malformed_output_detection)
                                                      + (SELECT count(*) FROM user_classifier_detection)"
expect "open detections are all span-grain"   3 "SELECT (SELECT count(*) FROM secret_leak_detection WHERE subject_span_id IS NOT NULL)
                                                      + (SELECT count(*) FROM malformed_output_detection WHERE subject_span_id IS NOT NULL)
                                                      + (SELECT count(*) FROM user_classifier_detection WHERE subject_span_id IS NOT NULL)"

if [ -n "$OVERLAY_DIR" ]; then
  echo "-- overlay lane --"
  # The overlay's fixture claims live beside its fixture, in the overlay, because an open script
  # never names an overlay relation (the ordering contract, epic 3 of the open-core execution
  # plan — overlay-owned since #1293). The file is a shell fragment that calls expect(); it is
  # sourced here with expect() and q() already defined.
  [ -f "$OVERLAY_EXPECTS" ] || die "MIGPOP_OVERLAY_EXPECTS ${OVERLAY_EXPECTS} does not exist"
  # shellcheck disable=SC1090
  . "$OVERLAY_EXPECTS"
else
  skip "overlay lane fixture coverage" "MIGPOP_OVERLAY_DIR is not set"
fi

if [ "$FAILURES" -gt 0 ]; then
  echo
  die "${FAILURES} fixture-coverage assertion(s) failed — the fixture no longer covers what this gate asserts on, so every SKIP below would be a lie"
fi

# ---------------------------------------------------------------- 3. open-new, overlay-new

echo
echo "check-migrations-populated: applying the open-new chain on top of populated tables"
liquibase_update "open new" "$WORK/resources" db/changelog/db.changelog-master.yaml

if [ -n "$OVERLAY_DIR" ]; then
  echo "check-migrations-populated: applying the overlay-new chain on top of populated tables"
  liquibase_update "overlay new" "$WORK/resources-overlay" db/changelog/paid/db.changelog-paid.yaml
fi

# ---------------------------------------------------------------- 4. release-block assertions
# One block per release with a migration in flight, each gated on a schema fact its own
# migration establishes, so a migration that has not landed reports SKIP rather than failing
# on rows nothing has migrated yet. Example shape, for whoever writes the next one:
#
#   echo
#   echo "Phase A — <what the release renames>"
#   if [ "$(q "SELECT to_regclass('public.<table the migration adds>') IS NOT NULL")" = "t" ]; then
#     expect "old value gone"  0 "SELECT count(*) FROM <t> WHERE <col>='<old>'"
#     expect "new value there" 1 "SELECT count(*) FROM <t> WHERE <col>='<new>'"
#   else
#     skip "Phase A" "<the schema fact> is absent — the migration has not landed"
#   fi
#

# ---------------------------------------------------------------- summary

echo
if [ "$KEEP" = 1 ]; then
  echo "check-migrations-populated: container kept — PGPASSWORD=${PASSWORD} psql -h localhost -p ${PORT} -U postgres -d ${DB}"
fi
if [ "$FAILURES" -gt 0 ]; then
  die "${FAILURES} assertion(s) failed against a populated database"
fi
LANE_MSG="open: ${NEW_COUNT} new changeset file(s)"
[ -n "$OVERLAY_DIR" ] && LANE_MSG="${LANE_MSG}, overlay: ${OVERLAY_NEW_COUNT} new changeset file(s)"
if [ "$NEW_COUNT" -eq 0 ] && { [ -z "$OVERLAY_DIR" ] || [ "$OVERLAY_NEW_COUNT" -eq 0 ]; }; then
  echo "check-migrations-populated: PASS — no changesets after either baseline (${LANE_MSG}); the chain(s) applied, the fixture(s) loaded and cover the vocabulary, ${SKIPPED} phase(s) skipped"
else
  echo "check-migrations-populated: PASS — ${LANE_MSG} applied to a populated database, ${SKIPPED} phase(s) skipped as not yet landed"
fi
