#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# =============================================================================
# Populated-database migration gate: run the new migrations against rows
# =============================================================================
# `task check` applies Liquibase to an empty Testcontainers database, and an empty database
# structurally cannot fail the two ways a rename fails:
#
#   1. `ALTER TABLE … ADD CONSTRAINT … CHECK (col = ANY (ARRAY['new', …]))` validates
#      every existing row. With no rows it always passes. With one row still holding
#      'old' it aborts the deploy, and that is the constraint swap a rename is made of.
#   2. `UPDATE … SET col='new' WHERE col='old'` that matches zero rows is
#      indistinguishable from one that matches all of them. Where no CHECK backs the
#      column nothing fails at all: the reader just starts seeing zero, not an error.
#
# So this script builds a database that has those rows, and asserts.
#
# Four steps against one throwaway container, in this order:
#
#   old chain          → the changelog up to and including MIGPOP_BASELINE, regenerated by
#                         cutting the current master's include list at that file.
#   fixture            → scripts/lib/populated-fixture.sql.
#   fixture-coverage   → a query per claim that a fixture row loaded. Runs before the new chain,
#                        so a table a migration drops is still queryable here.
#   new chain          → the current master, i.e. every migration after MIGPOP_BASELINE,
#                        applied on top of populated tables.
#   assertions         → one block per release with a migration in flight.
#
# WHY THE BASELINE IS A PINNED FILENAME AND NOT `git merge-base HEAD origin/main`. The fixture
# is written against one schema, the baseline's, and a merge-base cut produces that schema
# only while a release is unmerged. The moment it lands on main, every file in it exists at
# merge-base too, the "old" chain silently becomes the full chain, and the fixture fails to
# load against a schema its own release already renamed. The gate would then read as fixture
# rot rather than as a tool that had expired, and it would be runnable exactly once, by hand,
# before merge. Pinned, it stays runnable forever, which is what makes it a gate the next
# release can also point at its own renames.
#
# MOVING THE BASELINE. Bump it (or pass MIGPOP_BASELINE=) only
# together with a fixture that loads against the new baseline's schema and assertions that
# match, i.e. when a release's renames are done and the next release wants this vehicle.
# Bumping it alone turns the whole file into assertions about migrations that are already
# inside the "old" chain, which pass without proving anything.
#
# WHY THE LIQUIBASE CLI IMAGE. The app's only in-process Liquibase path is SpringLiquibase at
# boot, which needs the full application context (datasource, WorkOS config, the lot) to apply a
# changelog. The CLI image needs only a JDBC URL. Every apply here goes through the same tool,
# which is what makes the before/after comparison meaningful, and this database is throwaway, so
# nothing about the app's own runtime is being simulated or asserted. The image ships no Postgres
# driver, so the driver is taken from the local Maven repository the backend already builds against.
#
# NOT-YET-APPLICABLE ASSERTIONS. Each release's assertions go in a block gated on a schema fact
# its own migration establishes, so a migration that has not landed reports SKIP and never PASS:
# a gate that passes vacuously is worse than no gate.
#
# The fixture-coverage block runs always, and is the guard on the guard: it fails if a value this script asserts on never
# made it into the fixture, so a SKIP in the release-block section always means "the migration is
# not here yet", never "the row was not here either".
#
# Usage:  ./scripts/check-migrations-populated.sh [--keep]
#           --keep   leave the container running for poking at; prints the psql line
#
# Requires: docker and a Postgres JDBC driver in ~/.m2 (any backend build puts one
# there). Takes a couple of minutes on one CPU; leaves nothing behind.
#
# Not wired into `task check` or CI, deliberately: it is worth running exactly when a migration
# renames or narrows a persisted value, and it is dead weight on every other change. Run it per
# phase, `task migrations:populated`, before merging one that does.
# =============================================================================

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RESOURCES="backend/core/src/main/resources"
MASTER="$RESOURCES/db/changelog/db.changelog-master.yaml"

CONTAINER="tessary-migrations-populated"
NETWORK="tessary-migrations-populated-net"
# Deliberately not 5433 (the dev stack) or 55555 (restore-drill.sh): this must be
# runnable while either of those is up.
PORT="${MIGPOP_PORT:-55432}"
PG_IMAGE="${MIGPOP_PG_IMAGE:-pgvector/pgvector:pg16}"
LB_IMAGE="${MIGPOP_LB_IMAGE:-liquibase/liquibase:5.0}"
DB="tessary"
PASSWORD="migpop"
KEEP=0

# The last changeset the fixture is written against: everything after it is what this
# gate runs against rows. See "WHY THE BASELINE IS A PINNED FILENAME" above before moving it.
BASELINE="${MIGPOP_BASELINE:-0000-baseline.sql}"


[ "${1:-}" != "--keep" ] || KEEP=1

die() {
  echo "check-migrations-populated: FAIL — $*" >&2
  exit 1
}

WORK="$(mktemp -d -t tessary-migpop.XXXXXX)"
cleanup() {
  rm -rf "$WORK"
  if [ "$KEEP" != 1 ]; then
    docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
    docker network rm "$NETWORK" >/dev/null 2>&1 || true
  fi
}
trap cleanup EXIT

# ---------------------------------------------------------------- preflight

cd "$ROOT"
command -v docker >/dev/null || die "docker is required"
[ -f "$MASTER" ] || die "no master changelog at $MASTER"
[ -f scripts/lib/populated-fixture.sql ] || die "no fixture at scripts/lib/populated-fixture.sql"

DRIVER="$(find "$HOME/.m2/repository/org/postgresql/postgresql" -name 'postgresql-*.jar' 2>/dev/null \
  | grep -v -- '-sources' | sort -V | tail -1 || true)"
[ -n "$DRIVER" ] || die "no Postgres JDBC driver under ~/.m2 — build the backend once (mvn -f backend/pom.xml -q -DskipTests package) so the driver is resolved"

[ -f "$RESOURCES/db/changelog/changes/$BASELINE" ] || die "no baseline changeset at $RESOURCES/db/changelog/changes/$BASELINE"

# ---------------------------------------------------------------- the open changelogs
# The old master is the current master's include list cut at BASELINE. Deriving it from the
# CURRENT master (rather than checking out an old one) keeps the include order authoritative
# and means a reordering shows up here.

mkdir -p "$WORK/resources"
cp -R "$RESOURCES/db" "$WORK/resources/db"
CHANGELOG_DIR="$WORK/resources/db/changelog"

OLD_MASTER="$CHANGELOG_DIR/db.changelog-old.yaml"
{
  echo "# Generated by scripts/check-migrations-populated.sh — the chain through $BASELINE."
  echo "databaseChangeLog:"
} >"$OLD_MASTER"

NEW_FILES=""
OLD_COUNT=0
NEW_COUNT=0
PAST_BASELINE=0
while IFS= read -r file; do
  if [ "$PAST_BASELINE" = 0 ]; then
    printf '  - include:\n      file: %s\n      relativeToChangelogFile: false\n' "$file" >>"$OLD_MASTER"
    OLD_COUNT=$((OLD_COUNT + 1))
    [ "${file##*/}" != "$BASELINE" ] || PAST_BASELINE=1
  else
    NEW_FILES="$NEW_FILES ${file##*/}"
    NEW_COUNT=$((NEW_COUNT + 1))
  fi
done < <(sed -n 's|^ *file: *\(db/changelog/changes/.*\)$|\1|p' "$MASTER")

[ "$OLD_COUNT" -gt 0 ] || die "the generated old chain is empty — is $MASTER in the expected include format?"
[ "$PAST_BASELINE" = 1 ] || die "$BASELINE is on disk but not in $MASTER's include list — the baseline must be a changeset the chain actually applies"

echo "check-migrations-populated: old chain ${OLD_COUNT} file(s) through ${BASELINE}, new ${NEW_COUNT} file(s):${NEW_FILES:- none}"

# ---------------------------------------------------------------- throwaway postgres

docker rm -f "$CONTAINER" >/dev/null 2>&1 || true
docker network create "$NETWORK" >/dev/null 2>&1 || true
docker run --rm -d --name "$CONTAINER" --network "$NETWORK" \
  -e POSTGRES_PASSWORD="$PASSWORD" -e POSTGRES_DB="$DB" \
  -p "${PORT}:5432" "$PG_IMAGE" >/dev/null || die "could not start $PG_IMAGE on :${PORT}"

for _ in $(seq 1 90); do
  docker exec "$CONTAINER" pg_isready -U postgres >/dev/null 2>&1 && break
  sleep 1
done
docker exec "$CONTAINER" pg_isready -U postgres >/dev/null 2>&1 || die "postgres never became ready on :${PORT}"

# $2 is the resources root to mount; every apply goes through this one tool, see "WHY THE
# LIQUIBASE CLI IMAGE" above.
liquibase_update() {
  local label="$1" resources="$2" changelog="$3" log="$WORK/liquibase-${1// /-}.log"
  if ! docker run --rm --network "$NETWORK" \
      -v "$resources:/liquibase/changelog:ro" \
      -v "$DRIVER:/liquibase/lib/postgresql.jar:ro" \
      "$LB_IMAGE" --headless=true --logLevel=warning \
      --url="jdbc:postgresql://${CONTAINER}:5432/${DB}" --username=postgres --password="$PASSWORD" \
      --searchPath=/liquibase/changelog --changeLogFile="$changelog" \
      update >"$log" 2>&1; then
    # Stack frames drown the one line that matters ("… is violated by some row"), and
    # that line is the whole point of this gate, so they are filtered out.
    echo "--- liquibase output ($label chain, stack frames elided) ---" >&2
    { grep -v '^[[:space:]]*at ' "$log" || true; } | tail -30 >&2
    die "the ${label} chain did not apply"
  fi
}

q() {
  docker exec "$CONTAINER" psql -U postgres -d "$DB" -tAc "$1" 2>/dev/null | tr -d '[:space:]'
}

# ---------------------------------------------------------------- assertions plumbing

FAILURES=0
SKIPPED=0
expect() {
  local label="$1" want="$2" sql="$3" got
  got="$(q "$sql" || true)"
  if [ "$got" = "$want" ]; then
    printf '  PASS  %-58s %s\n' "$label" "$got"
  else
    printf '  FAIL  %-58s got %s, want %s\n' "$label" "${got:-<query error>}" "$want"
    FAILURES=$((FAILURES + 1))
  fi
}
skip() {
  printf '  SKIP  %-58s %s\n' "$1" "$2"
  SKIPPED=$((SKIPPED + 1))
}

# ---------------------------------------------------------------- 1. old chain, fixture

echo "check-migrations-populated: applying the old chain"
liquibase_update "old" "$WORK/resources" db/changelog/db.changelog-old.yaml

echo "check-migrations-populated: loading the fixture"
docker exec -i "$CONTAINER" psql -v ON_ERROR_STOP=1 -U postgres -d "$DB" -q \
  <scripts/lib/populated-fixture.sql \
  || die "the fixture did not load against the old chain — it has drifted from the schema through ${BASELINE}"

echo
echo "fixture coverage (every value a rename could touch must be present BEFORE the new chain)"
expect "job.kind='classifier'"                1 "SELECT count(*) FROM job WHERE kind='classifier'"
expect "classifier rows"                      2 "SELECT count(*) FROM classifier"
expect "frustration built-in enabled (pre-0022)" 1 "SELECT count(*) FROM classifier
                                                      WHERE classifier_key='frustration' AND built_in AND enabled"
expect "eval_case.detector='classifier'"      3 "SELECT count(*) FROM eval_case WHERE detector='classifier'"
expect "eval_case both finding arms"          3 "SELECT (SELECT count(*) FROM eval_case WHERE finding_id IS NOT NULL)
                                                      + (SELECT count(*) FROM eval_case WHERE finding_id IS NULL AND state='resolved')"
expect "finding rows"                         8 "SELECT count(*) FROM finding"
expect "secret_leak findings open, unruled, one per band (pre-0013)" "high,low" "SELECT string_agg(payload->>'confidence', ',' ORDER BY payload->>'confidence')
                                                      FROM finding WHERE classifier_key='secret_leak' AND status='open' AND triage_verdict IS NULL"
expect "finding ruled unclear (pre-0010)"     1 "SELECT count(*) FROM finding WHERE triage_verdict='unclear'"
expect "finding legacy statuses (pre-0011)"   3 "SELECT count(*) FROM finding WHERE status IN ('blocked','allowlisted','graduated')"
expect "finding open+positive backing a live case (pre-0011)" 1 "SELECT count(*) FROM finding
                                                      WHERE id='fnd_fix_open_cased' AND status='open' AND triage_verdict='positive'"
expect "eval_case backing the open+positive finding" 1 "SELECT count(*) FROM eval_case
                                                      WHERE finding_id='fnd_fix_open_cased' AND state<>'resolved'"
expect "annotation all three grains"          3 "SELECT count(DISTINCT subject_kind) FROM annotation"
expect "failure_mode_instance both grains"    2 "SELECT count(DISTINCT subject_kind) FROM failure_mode_instance"
expect "metric_rollup metering metrics"       2 "SELECT count(*) FROM metric_rollup WHERE metric IN ('l1_evals','l2_evals')"
expect "metric_baseline row"                  1 "SELECT count(*) FROM metric_baseline WHERE bucket_key='cs_fix'"
expect "retention_policy both classes"        2 "SELECT count(DISTINCT data_class) FROM retention_policy
                                                   WHERE data_class IN ('traces','detections')"
expect "alert_event payload classifier keys"  1 "SELECT count(*) FROM alert_event WHERE payload_json LIKE '%\"classifiers\"%' AND payload_json LIKE '%\"classifier_key\"%'"
expect "pre_deploy_check rows"                1 "SELECT count(*) FROM pre_deploy_check"
expect "telemetry_install row"                1 "SELECT count(*) FROM telemetry_install"
# The old six-table detection UNION view is gone; these are its three open arms, asked
# directly. All three fixture rows are span-grain (see scripts/lib/populated-fixture.sql), which
# is the fact this checks rather than assuming.
expect "open detection rows across the three open tables" 3 "SELECT (SELECT count(*) FROM secret_leak_detection)
                                                      + (SELECT count(*) FROM malformed_output_detection)
                                                      + (SELECT count(*) FROM user_classifier_detection)"
expect "open detections are all span-grain"   3 "SELECT (SELECT count(*) FROM secret_leak_detection WHERE subject_span_id IS NOT NULL)
                                                      + (SELECT count(*) FROM malformed_output_detection WHERE subject_span_id IS NOT NULL)
                                                      + (SELECT count(*) FROM user_classifier_detection WHERE subject_span_id IS NOT NULL)"

if [ "$FAILURES" -gt 0 ]; then
  echo
  die "${FAILURES} fixture-coverage assertion(s) failed — the fixture no longer covers what this gate asserts on, so every SKIP below would be a lie"
fi

# ---------------------------------------------------------------- 2. new chain

echo
echo "check-migrations-populated: applying the new chain on top of populated tables"
liquibase_update "new" "$WORK/resources" db/changelog/db.changelog-master.yaml

# ---------------------------------------------------------------- 3. release-block assertions
# One block per release with a migration in flight, each gated on a schema fact its own
# migration establishes, so a migration that has not landed reports SKIP rather than failing
# on rows nothing has migrated yet. Example shape, for whoever writes the next one:
#
#   echo
#   echo "Phase A: <what the release renames>"
#   if [ "$(q "SELECT to_regclass('public.<table the migration adds>') IS NOT NULL")" = "t" ]; then
#     expect "old value gone"  0 "SELECT count(*) FROM <t> WHERE <col>='<old>'"
#     expect "new value there" 1 "SELECT count(*) FROM <t> WHERE <col>='<new>'"
#   else
#     skip "Phase A" "<the schema fact> is absent, the migration has not landed"
#   fi
#

echo
echo "0008: telemetry_install becomes telemetry_instance"
if [ "$(q "SELECT to_regclass('public.telemetry_instance') IS NOT NULL")" = "t" ]; then
  expect "telemetry_install gone"               t "SELECT to_regclass('public.telemetry_install') IS NULL"
  expect "instance_id kept the fixture UUID"    3f2504e0-4f89-41d3-9a0c-0305e82c3301 "SELECT instance_id FROM telemetry_instance"
  expect "ping_seq survived the rename"         0 "SELECT ping_seq FROM telemetry_instance"
else
  skip "0008 telemetry instance rename" "telemetry_instance is absent, 0008 has not landed"
fi

echo
echo "0010: triage verdict narrows to positive/negative"
if [ "$(q "SELECT NOT EXISTS (SELECT 1 FROM pg_constraint
                                WHERE conname = 'finding_triage_verdict_check'
                                  AND pg_get_constraintdef(oid) LIKE '%unclear%')")" = "t" ]; then
  expect "no finding still reads unclear"       0 "SELECT count(*) FROM finding WHERE triage_verdict='unclear'"
  expect "the fixture's unclear finding is now negative" negative "SELECT triage_verdict FROM finding WHERE id='fnd_fix_unclear'"
  expect "its action is untouched by the rewrite" closed "SELECT triage_action FROM finding WHERE id='fnd_fix_unclear'"
else
  skip "0010 triage verdict binary" "finding_triage_verdict_check still allows unclear, 0010 has not landed"
fi

echo
echo "0011: findings are open or closed; eval_case.finding_id becomes finding.case_id"
if [ "$(q "SELECT EXISTS (SELECT 1 FROM information_schema.columns
                            WHERE table_name='finding' AND column_name='case_id')")" = "t" ]; then
  expect "finding_status_check no longer allows graduated" f "SELECT EXISTS (SELECT 1 FROM pg_constraint
                                WHERE conname='finding_status_check'
                                  AND pg_get_constraintdef(oid) LIKE '%graduated%')"
  expect "eval_case.finding_id is gone"         f "SELECT EXISTS (SELECT 1 FROM information_schema.columns
                                WHERE table_name='eval_case' AND column_name='finding_id')"
  expect "eval_case.locked_at exists"           t "SELECT EXISTS (SELECT 1 FROM information_schema.columns
                                WHERE table_name='eval_case' AND column_name='locked_at')"
  expect "finding.recurrences_since_verdict is gone" f "SELECT EXISTS (SELECT 1 FROM information_schema.columns
                                WHERE table_name='finding' AND column_name='recurrences_since_verdict')"
  expect "eval_case_event_kind_check allows recurred" t "SELECT EXISTS (SELECT 1 FROM pg_constraint
                                WHERE conname='eval_case_event_kind_check'
                                  AND pg_get_constraintdef(oid) LIKE '%recurred%')"
  # A person's ruling (blocked), no case standing on it: closes, with the fixed positive summary.
  # (q() strips whitespace for the comparison, so the summary check asks Postgres for a boolean
  # rather than round-tripping the sentence through a whitespace-hostile shell comparison.)
  expect "blocked -> closed/positive"           "closed|positive" "SELECT status || '|' || triage_verdict
                                FROM finding WHERE id='fnd_fix_blocked'"
  expect "blocked's fixed summary"              t "SELECT triage_summary = 'A person ruled this a real deviation.'
                                FROM finding WHERE id='fnd_fix_blocked'"
  # A person's ruling (allowlisted), no verdict yet: closes negative with the fixed summary.
  expect "allowlisted -> closed/negative"       "closed|negative" "SELECT status || '|' || triage_verdict
                                FROM finding WHERE id='fnd_fix_allowlisted'"
  # An old status this migration never names: closes, with no verdict to show for it.
  expect "graduated -> closed, no verdict"      "closed|" "SELECT status || '|' || COALESCE(triage_verdict, '')
                                FROM finding WHERE id='fnd_fix_graduated'"
  # The one shape that must survive open: a positive ruling backing a still-live case, linked
  # through the new reverse pointer.
  expect "open+positive stays open, case-linked" "open|ec_fix_open_cased" "SELECT status || '|' || case_id
                                FROM finding WHERE id='fnd_fix_open_cased'"
else
  skip "0011 finding open/closed" "finding.case_id is absent, 0011 has not landed"
fi

echo
echo "0013: high-confidence secret leaks are ruled positive"
if [ "$(q "SELECT EXISTS (SELECT 1 FROM databasechangelog WHERE id='0013-rule-high-confidence-leaks')")" = "t" ]; then
  expect "high leak -> open/positive/opened_case" "open|positive|opened_case" "SELECT status || '|' || triage_verdict || '|' || triage_action
                                FROM finding WHERE id='fnd_fix_leak_high'"
  expect "high leak's fixed summary"            t "SELECT triage_summary = 'A high-confidence credential pattern matched in the agent''s output, so this leak was ruled real without triage.'
                                FROM finding WHERE id='fnd_fix_leak_high'"
  expect "high leak's triaged_at parses as a timestamp" t "SELECT CAST(triaged_at AS timestamptz) IS NOT NULL
                                FROM finding WHERE id='fnd_fix_leak_high'"
  expect "low leak stays open and unruled"      "open|" "SELECT status || '|' || COALESCE(triage_verdict, '')
                                FROM finding WHERE id='fnd_fix_leak_low'"
else
  skip "0013 rule high-confidence leaks" "0013 is not in databasechangelog, it has not landed"
fi

echo
echo "0022: frustration ships off"
if [ "$(q "SELECT EXISTS (SELECT 1 FROM databasechangelog WHERE id='0022-frustration-off')")" = "t" ]; then
  expect "frustration built-in is disabled"     f "SELECT enabled FROM classifier WHERE id='cls_fix_frustration'"
  expect "its updated_at parses as a timestamp" t "SELECT CAST(updated_at AS timestamptz) > '2026-01-01T00:00:00Z'
                                FROM classifier WHERE id='cls_fix_frustration'"
  expect "the fixture classifier is untouched"  t "SELECT enabled FROM classifier WHERE id='cls_fix'"
  expect "frustration_detection is empty"       0 "SELECT count(*) FROM frustration_detection"
else
  skip "0022 frustration off" "0022 is not in databasechangelog, it has not landed"
fi

# ---------------------------------------------------------------- summary

echo
if [ "$KEEP" = 1 ]; then
  echo "check-migrations-populated: container kept — PGPASSWORD=${PASSWORD} psql -h localhost -p ${PORT} -U postgres -d ${DB}"
fi
if [ "$FAILURES" -gt 0 ]; then
  die "${FAILURES} assertion(s) failed against a populated database"
fi
if [ "$NEW_COUNT" -eq 0 ]; then
  echo "check-migrations-populated: PASS — no changesets after the baseline; the chain applied, the fixture loaded and covers the vocabulary, ${SKIPPED} phase(s) skipped"
else
  echo "check-migrations-populated: PASS — ${NEW_COUNT} new changeset file(s) applied to a populated database, ${SKIPPED} phase(s) skipped as not yet landed"
fi
